### ISSUE TITLE
Unable to start server. Problem with SocketIO?

### ISSUE THREAD

**Issue by ghost** [juharris/switch-remoteplay#70]
When running `sudo SECRET_KEY='something random-ish' python3 switchremoteplay/server.py`, I get this error. I have changed the SECRET_KEY to various values to no success.

Line 8 from the log from server.py being `flask_socketio import SocketIO`
```
Traceback (most recent call last):
  File "/home/myuser/switch-remoteplay/server/switchremoteplay/server.py", line 8, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.10/dist-packages/flask_socketio/__init__.py", line 9, in <module>
    from socketio import socketio_manage  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/usr/local/lib/python3.10/dist-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/usr/local/lib/python3.10/dist-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python3.10/dist-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/local/lib/python3.10/dist-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/usr/local/lib/python3.10/dist-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/usr/local/lib/python3.10/dist-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/usr/local/lib/python3.10/dist-packages/eventlet/greenio/base.py", line 32, in <module>
    socket_timeout = eventlet.timeout.wrap_is_timeout(socket.timeout)
  File "/usr/local/lib/python3.10/dist-packages/eventlet/timeout.py", line 166, in wrap_is_timeout
    base.is_timeout = property(lambda _: True)
TypeError: cannot set 'is_timeout' attribute of immutable type 'TimeoutError'
```
For reference, I have tried running this on a Raspbian and also a Ubuntu virtual machine. Both have the same error. I'm wondering if I'm missing some sort of dependency here.

Please help me out if you're able to.

**Comment by JCionx** [comment]
Have you solved this issue? I'm having the same problem.
